CREATE TABLE ACTOR (
    ID_PERSONALITY VARCHAR(40) REFERENCES PERSONALITY(id_personality),
    ID_FILM VARCHAR(40) REFERENCES film(id_film),
    CHARACTER varchar(255),
    ROLE varchar(255)
);
CREATE TABLE CREATORS (
    ID_FILM VARCHAR(40) REFERENCES film(id_film),
    ID_PERSONALITY VARCHAR(40) REFERENCES PERSONALITY(id_personality),
    ID_POSITION VARCHAR(40) REFERENCES position(id_position)
);