CREATE TABLE PERSONALITY (
    ID_PERSONALITY VARCHAR(40) PRIMARY KEY NOT NULL,
    NAME_PERSONALITY VARCHAR(255) NOT NULL,
    DOB_PERSONALITY date
);
CREATE TABLE POSITION (
    ID_POSITION VARCHAR(40) PRIMARY KEY NOT NULL,
    NAME_POSITION VARCHAR(100) NOT NULL
);